GET http://localhost:3000/users/email/johndoe@example1.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlMS5jb20iLCJpYXQiOjE3MzAzODU1OTcsImV4cCI6MTczMDM4OTE5NywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.mgzYn_PdTz1z1YCsxV0PEJhXhZAf0vU0oQg8kTq-rx0

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlMS5jb20iLCJpYXQiOjE3MzAzODU1OTcsImV4cCI6MTczMDM4OTE5NywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.mgzYn_PdTz1z1YCsxV0PEJhXhZAf0vU0oQg8kTq-rx0
